// add the immutable classes outside of your codebase
// java.time.LocalDate

// alternatively you can stabilize all java.time classes with *
// java.time.*

// stabilize all classes in model package
// This way, the domain module can be a Java Gradle module and doesn’t need dependency on the Compose compiler.
// com.example.app.domain.model.*